Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.1/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import astropy.units as u
from astropy.coordinates import SkyCoord
from imephu.salt.finder_chart import GeneralProperties, MagnitudeRange, Target

position = SkyCoord(ra="15h 49m 49.5s", dec="âˆ’29Â° 23â€² 13â€³")
survey = "POSS2/UKSTU Red"
general_properties = GeneralProperties(
    target=Target(
        name="NGC 6000",
        position=position,
        magnitude_range=MagnitudeRange(
            bandpass="V",
            min_magnitude=11.3,
            max_magnitude=11.3
        )
    ),
    position_angle=0 * u.deg,
    automated_position_angle=False,
    proposal_code="2022-1-SCI-042",
    pi_family_name="Doe",
    survey=survey
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 3>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01munits[39;00m [38;5;28;01mas[39;00m [38;5;21;01mu[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mastropy[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcoordinates[39;00m [38;5;28;01mimport[39;00m SkyCoord
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mimephu[39;00m[38;5;21;01m.[39;00m[38;5;21;01msalt[39;00m[38;5;21;01m.[39;00m[38;5;21;01mfinder_chart[39;00m [38;5;28;01mimport[39;00m GeneralProperties, MagnitudeRange, Target
[1;32m      5[0m position [38;5;241m=[39m SkyCoord(ra[38;5;241m=[39m[38;5;124m"[39m[38;5;124m15h 49m 49.5s[39m[38;5;124m"[39m, dec[38;5;241m=[39m[38;5;124m"[39m[38;5;124mâˆ’29Â° 23â€² 13â€³[39m[38;5;124m"[39m)
[1;32m      6[0m survey [38;5;241m=[39m [38;5;124m"[39m[38;5;124mPOSS2/UKSTU Red[39m[38;5;124m"[39m

[0;31mModuleNotFoundError[0m: No module named 'imephu'
ModuleNotFoundError: No module named 'imephu'

